-----------------------------------------------
-- Load DB DDL and DML
-----------------------------------------------

CREATE SCHEMA OMPRUEBA;

CREATE TABLE OMPRUEBA."ORDER_STATUS_ENUM" (
    STATUS INT PRIMARY KEY,
    DESCRIPTION TEXT
);

CREATE TABLE OMPRUEBA."ORDER" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    ITEMS INT NOT NULL,
    BASE_AMOUNT DECIMAL(10, 2) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    STATUS INT NOT NULL,
    FOREIGN KEY (STATUS) REFERENCES OMPRUEBA."ORDER_STATUS_ENUM"(STATUS)
);

CREATE TABLE OMPRUEBA."PRODUCT" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE OMPRUEBA."ORDER_PRODUCT" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES OMPRUEBA."ORDER"(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES OMPRUEBA."PRODUCT"(ID)
);

-- ORDER STATUSES
INSERT INTO OMPRUEBA."ORDER_STATUS_ENUM" (STATUS, DESCRIPTION) VALUES
(1, 'PENDIENTE'),
(2, 'COBRADO'),
(3, 'ENVIADO'),
(4, 'RECIBIDO'),
(5, 'ANULADO')
;

-- PRODUCT TEST DATA (from requirements file)
INSERT INTO OMPRUEBA."PRODUCT" (NAME, DESCRIPTION, PRICE) VALUES
('Cemento', 'Saco de cemento Portland para construcción.', 25.00),
('Ladrillos', 'Paquete de ladrillos cerámicos para edificación.', 1.20),
('Madera para construcción', 'Tablones de madera tratada para uso en proyectos de construcción.', 15.00)
;

-- ORDER TEST DATA (from requirements file)
INSERT INTO OMPRUEBA."ORDER" (DATE, ITEMS, BASE_AMOUNT, AMOUNT, STATUS) VALUES
('2024-02-19 12:30:00+00', 2, 67.40, 77.51, 1),
('2024-02-19 14:45:00+00', 1, 1.20, 1.38, 5),
('2024-02-19 16:00:00+00', 3, 44.10, 50.76, 2)
;