-- Just for testing purposes
--DROP SCHEMA OMPRUEBA CASCADE;
--ALTER TABLE OMPRUEBA."ORDER" ALTER COLUMN ID RESTART WITH 1;

CREATE SCHEMA OMPRUEBA;

CREATE TABLE OMPRUEBA."ORDER_STATUS_ENUM" (
    STATUS SMALLINT PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE OMPRUEBA."ORDER" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    ITEMS SMALLINT NOT NULL,
    BASE_AMOUNT DECIMAL(10, 2) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    STATUS SMALLINT NOT NULL,
    FOREIGN KEY (STATUS) REFERENCES OMPRUEBA."ORDER_STATUS_ENUM"(STATUS)
);

CREATE TABLE OMPRUEBA."PRODUCT" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE OMPRUEBA."ORDER_PRODUCT" (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES OMPRUEBA."ORDER"(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES OMPRUEBA."PRODUCT"(ID)
);
